import Head from "next/head";
import ProudStories from "./components/ProudStories.js";
import About from "./components/About";

export default function Home() {
  return (
    <div className="page_background ">
      <Head>
        <title>Cetal Deve Solutions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <About />
        </div>
        <div >
          <div className=" uppercase font-semibold pt-5 text-center text-3xl p-2 border-4 text-cyan-500">
            PROUD STORIES
          </div>
          <div className="sm:max-w-screen">
            <ProudStories />
          </div>
        </div>
      </main>
    </div>
  );
}
